// src/constants/routes.ts
export const ROUTES = {
  HOME:         "/",
  MODE:         "/mode",
  STRATEGIES:   "/strategies",
  BROKERS:      "/brokers",
  BROKER_DETAIL: (brokerId: string) => `/brokers/${brokerId}`,
  BACKTEST:     "/backtest",
  RISK:         "/risk",
  NEWS:         "/news",
  FUNDAMENTALS: "/fundamentals",
  ALERTS:       "/alerts",
  ADMIN:        "/admin",
  AUDIT:        "/audit",
  OPTIONS:      (symbol: string) => `/options/${symbol}`,
  DISCOVER:       "/discover",
  BRIEFING:       "/briefing",
  LLM:            "/llm",
  NOTIFICATIONS:         "/notifications",
  SEND_ALERTS:           "/admin/send-alerts",
  COPY_TRADING:                 "/copy-trading/connections",
  COPY_TRADING_TELEGRAM:        "/copy-trading/connections/telegram",
  COPY_TRADING_DISCORD:         "/copy-trading/connections/discord",
  COPY_TRADING_DISCORD_RETURN:  "/copy-trading/discord",
  COPY_TRADING_DISCORD_ACCOUNT: "/copy-trading/connections/discord-account",
  COPY_TRADING_X:               "/copy-trading/connections/x",
  COPY_TRADING_VALIDATOR:       "/copy-trading/validator",
  COPY_TRADING_MISSING_FIELDS:  "/copy-trading/missing-fields",
  COPY_TRADING_ORDERS:          "/copy-trading/orders",
  COPY_TRADING_SIGNALS:         "/copy-trading/signals",
  COPY_TRADING_OPEN_TRADES:     "/copy-trading/open-trades",
  COPY_TRADING_OPEN_TRADE:      (id: string) => `/copy-trading/open-trades/${id}`,
  COPY_TRADING_REVIEW_QUEUE:    "/copy-trading/review-queue",
  LOGIN:                        "/login",
} as const;

// Nav items for sidebar — order matches page map from spec.
// `subtitle` = the secondary line shown under the page title in the topbar.
// Use the literal "__live_clock__" sentinel to render a live date/time clock.
export const NAV_ITEMS = [
  { to: ROUTES.HOME,         label: "Dashboard",     icon: "▦", subtitle: "__live_clock__" },
  { to: ROUTES.MODE,         label: "Trading Mode",  icon: "⇄", subtitle: "Select how the platform executes trades on your behalf" },
  { to: ROUTES.STRATEGIES,   label: "Strategies",    icon: "◈", subtitle: "Manage and monitor all deployed trading strategies" },
  { to: ROUTES.BROKERS,      label: "Brokers",       icon: "⬡", subtitle: "Connected brokerage and exchange accounts" },
  { to: ROUTES.BACKTEST,     label: "Backtest",      icon: "◷", subtitle: "Replay strategies against historical data" },
  { to: ROUTES.RISK,         label: "Risk Panel",    icon: "⚠", subtitle: "Live exposure, drawdown, and risk limits" },
  { to: ROUTES.NEWS,         label: "News Feed",     icon: "◉", subtitle: "Real-time market news and headlines" },
  { to: ROUTES.FUNDAMENTALS, label: "Fundamentals",  icon: "◎", subtitle: "Company financials and ratios" },
  { to: ROUTES.ALERTS,       label: "Alerts",        icon: "◆", subtitle: "Triggered notifications and watchlists" },
  { to: ROUTES.OPTIONS,      label: "Options Chain", icon: "⊞", subtitle: "Strikes, greeks, and options analytics" },
  { to: ROUTES.DISCOVER,     label: "Discovery",     icon: "⊹", subtitle: "Find new opportunities across markets" },
  { to: ROUTES.BRIEFING,     label: "Briefing",      icon: "☀", subtitle: "Daily market briefing and outlook" },
  { to: ROUTES.LLM,          label: "LLM Config",    icon: "⊛", subtitle: "Tune the AI models powering the platform" },
  { to: ROUTES.COPY_TRADING,  label: "Copy Trading",  icon: "⊕", subtitle: "Connect signal sources to copy trades" },
  { to: ROUTES.AUDIT,        label: "Audit Trail",   icon: "≡", subtitle: "Every action, signed and timestamped" },
  { to: ROUTES.ADMIN,         label: "Admin",         icon: "⚙", subtitle: "Users, roles, and platform configuration" },
  { to: ROUTES.SEND_ALERTS,   label: "Send Alerts",   icon: "⊟", subtitle: "Dispatch notifications via Telegram, Discord, or platform", adminOnly: true },
  { to: ROUTES.NOTIFICATIONS, label: "Notifications",  icon: "◉", subtitle: "Your notification inbox", hidden: true },
] as const;
